#!/usr/bin/env bash
# installs nginx and configures it on a remote server
#apt-get -y update
#apt-get -y install nginx
#ufw allow 'Nginx HTTP'
#echo 'Hello World!' > /var/www/html/index.html
#service nginx start
# Update the package list and install nginx
sudo apt-get update -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -s reload
