#!/usr/bin/env bash

# Update package list and install prerequisites
sudo apt-get update
sudo apt-get install -y software-properties-common

# Add HAProxy PPA and install HAProxy version 1.8
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install -y haproxy=1.8.\*

# Enable HAProxy to start on boot
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Configure HAProxy to listen to web-01 and web-02 servers
cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 517148-web-01 100.25.165.20:80 check
    server 517148-web-02 52.91.133.191:80 check
EOT

# Restart HAProxy to apply the configuration
sudo service haproxy restart
