#!/usr/bin/env bash

# Allow traffic on port 8080
sudo ufw allow 8080/tcp

# Add Port Forwarding Rule to before.rules
sudo tee -a /etc/ufw/before.rules <<EOL
# Port forwarding rule for redirecting 8080 to 80
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]

# Redirect traffic from port 8080 to 80
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80

COMMIT
EOL

# Reload UFW to apply changes
sudo ufw reload

# Display UFW status
sudo ufw status verbose
